name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Notify build failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "No1is / Sam Meir Pokedex part 11 hook"
          status: failure
          title: "Build failed"
          description: | 
            Commit <https://github.com/${{ github.repository }}/commit/${{ github.sha }}> 
            Actor: **${{ github.actor }}** broke the build :("
            Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Test
        run: npm run test
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Test end 2 end
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && !contains(toJson(github.event.commits), '#skip')  }}
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
      - name: Deploy success notification
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "No1is / Sam Meir Pokedex part 11 hook"
          status: success
          title: "A new version of Pokedex deployed"
          description: |
            • Repo: **${{ github.repository }}**
            • Actor: **${{ github.actor }}**
            • Run: [View logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          content: "✅ Deployment finished successfully!"
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && !contains(toJson(github.event.commits), '#skip')  }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          RELEASE_BRANCHES: main
