name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Notify build failure
        uses: rjstone/discord-webhook-notify@v2.2.1
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: "No1is / Sam Meir Pokedex part 11 hook"
          severity: error
          title: "Build failed"
          description: "Commit <https://github.com/${{ github.repository }}/commit/${{ github.sha }}> by **${{ github.actor }}** broke the build :("
          color: 15158332
      - name: Test
        run: npm run test
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Test end 2 end
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && !contains(toJson(github.event.commits), '#skip')  }}
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
      - name: Deploy success notification
        uses: rjstone/discord-webhook-notify@v2.2.1
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: "No1is / Sam Meir Pokedex part 11 hook"
          severity: info
          title: "A new version of Pokedex deployed"
          description: "to <https://pokedex-zegp.onrender.com> by **${{ github.actor }}**"
          color: 3066993
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && !contains(toJson(github.event.commits), '#skip')  }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          RELEASE_BRANCHES: main
